### ISSUE TITLE
how do i go about inserting HTML into my pdf?

### ISSUE THREAD

**Issue by multinerd** [ritchiecarroll/Report.NET#3]

**Comment by ritchiecarroll** [comment]
The Report.NET library allows you to create a PDF by programmatically placing text and images at desired locations in the document. In order to insert HTML in the PDF you would first need to parse and render the HTML so that the elements and their positions could be placed within the PDF document. Your other option would be to take a image snapshot of the rendered HTML and inject the image into the PDF document. There is not a function in the library to automatically inject and render HTML into the PDF.

Hope that helps!

**Comment by multinerd** [comment]
Thanks, i ended up using teleriks reporting software. its a hefty price but it covers what i needed.
